name: buzz_string
description: "BuzzString - Badminton Stringing Service App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_dotenv: ^6.0.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.5.1
  shared_preferences: ^2.2.2

  flutter:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  google_sign_in: ^6.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/strings/
    - rackets.txt
    - assets/images/google_logo.png
    - assets/images/buzz_string_logo.png
    - assets/images/zelle_logo.png
    - assets/images/cash_logo.png
