// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6lhzZdwSwhjOz0PAinJJAlRheTy-wi0',
    appId: '1:74843313203:web:d4558f13122b8a9a237f46',
    messagingSenderId: '74843313203',
    projectId: 'buzzstring-5c3df',
    authDomain: 'buzzstring-5c3df.firebaseapp.com',
    storageBucket: 'buzzstring-5c3df.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCA3Xm-aYpFShzgteJ5x2qSe4-QQsj0mA',
    appId: '1:74843313203:android:61724e59352d998e237f46',
    messagingSenderId: '74843313203',
    projectId: 'buzzstring-5c3df',
    storageBucket: 'buzzstring-5c3df.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTa92m6DSdYrPPWhsS4UMqXq0_2hn3_To',
    appId: '1:74843313203:ios:9dd0171fee72f929237f46',
    messagingSenderId: '74843313203',
    projectId: 'buzzstring-5c3df',
    storageBucket: 'buzzstring-5c3df.firebasestorage.app',
    iosClientId:
        '74843313203-l9luhobck6m6d61jn2kernlepqo7g9a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzString',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTa92m6DSdYrPPWhsS4UMqXq0_2hn3_To',
    appId: '1:74843313203:ios:9dd0171fee72f929237f46',
    messagingSenderId: '74843313203',
    projectId: 'buzzstring-5c3df',
    storageBucket: 'buzzstring-5c3df.firebasestorage.app',
    iosClientId:
        '74843313203-l9luhobck6m6d61jn2kernlepqo7g9a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzzString',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6lhzZdwSwhjOz0PAinJJAlRheTy-wi0',
    appId: '1:74843313203:web:6d75458e8f245298237f46',
    messagingSenderId: '74843313203',
    projectId: 'buzzstring-5c3df',
    authDomain: 'buzzstring-5c3df.firebaseapp.com',
    storageBucket: 'buzzstring-5c3df.firebasestorage.app',
  );
}
